### ISSUE TITLE
Error in loadNamespace(name) thrown up when running highmapsChoropleth() example

### ISSUE THREAD

**Issue by aashanand** [bthieurmel/highchartsUtils#1]
Hi, can you check whether this error is reproducible? It's basically the first example I tried and i'm getting this error. Tried to install package 'RTEgraphics' and looked all over for it, to no avail.    

```
data(UE)
head(UE)
UE$value <- rnorm(nrow(UE), 50,100)

res <- highmapsChoropleth(UE, value ="value", key = "hc-key", title = "Exemple UE",
                                            scope = "UE")
Error in loadNamespace(name) : there is no package called ‘RTEgraphics’
```

**Comment by bthieurmel** [comment]
Hi, 
I fix this little bug, It was a little forgetting during last update. I don't use this package actually (it's a old project...), but highmapsChoropleth is quite cool.
